version: '3.1'
services:
  db:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: anime
    ports:
    - "3306:3306"
    volumes:
      - isaacdev_data:/var/lib/mysql

volumes:
  isaacdev_data:
